#!/bin/bash -eu

source /var/vcap/packages/golang-1.12-linux/bosh/runtime.env

export GO_BINARY_PATH=/var/vcap/packages/golang-1.12-linux/bin/go
export PATH=/var/vcap/packages/git/bin:$PATH

exec /var/vcap/packages/athens/bin/athens \
  -config_file /var/vcap/jobs/athens/config/athens.toml