name: Build Status

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  push:
    branches:
    - master

jobs:
  test:
    name: Athens Integration Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run tests against bosh on docker
        uses: s4heid/bosh-action@master
        with:
          script: ./ci/actions/test.sh
